##
## compiling tcpreplay from source
##

FROM bitnami/minideb:stretch as tcpreplay

ARG RELEASE=4.3.0

RUN install_packages \
  build-essential \
  ca-certificates \
  curl \
  file \
  libpcap-dev \
  tcpdump && \
  cd /tmp && \
  curl -sSfL https://github.com/appneta/tcpreplay/releases/download/v${RELEASE}/tcpreplay-${RELEASE}.tar.xz | tar -xJv && \
  cd tcpreplay-${RELEASE} && \
  # replace the occurrences of ETH_P_ALL with ETH_P_IP
  sed -i 's|ETH_P_ALL|'"ETH_P_IP"'|g' src/common/sendpacket.c && \
  ./configure && \
  make && \
  make install


##
## development image with DPDK and Rust
##

FROM williamofockham/dpdk:17.08.1-dev

ARG RUSTUP_TOOLCHAIN=nightly-2018-12-01
ARG BACKPORTS_REPOFILE=/etc/apt/sources.list.d/stretch-backports.list

ENV PATH=$PATH:/root/.cargo/bin
ENV LD_LIBRARY_PATH=/opt/netbricks/target/native:$LD_LIBRARY_PATH

COPY --from=tcpreplay /usr/local/bin /usr/local/bin
COPY --from=tcpreplay /usr/local/share/man/man1 /usr/local/share/man/man1

RUN install_packages \
  # clang, libclang-dev and libsctp-dev are netbricks deps
  build-essential \
  ca-certificates \
  clang \
  curl \
  libclang-dev \
  libsctp-dev \
  tcpdump && \
  # install luajit 2.1.0-beta3 from stretch backports
  echo "deb http://ftp.debian.org/debian stretch-backports main" > ${BACKPORTS_REPOFILE} && \
  apt-get update -o Dir::Etc::sourcelist=${BACKPORTS_REPOFILE} && \
  apt-get -t stretch-backports install -y --no-install-recommends libluajit-5.1-dev && \
  rm -r /var/lib/apt/lists /var/cache/apt/archives && \
  # install rust nightly
  curl -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain $RUSTUP_TOOLCHAIN
